import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import EmptyState from "../components/common/EmptyState";
import PageHeader from "../components/common/PageHeader";
import { useDataset } from "../context/DatasetContext";
import { formatCompactCurrency, formatCurrency, formatNumber, formatPercent, formatRoas } from "../utils/formatters";

export default function Channels() {
  const { dataset, report } = useDataset();
  if (!dataset || !report) return <main className="content-wrap"><PageHeader eyebrow="CHANNEL MIX" title="Channel performance" description="Understand spend, return and conversion efficiency by channel." /><EmptyState /></main>;
  return <main className="content-wrap"><PageHeader eyebrow="CHANNEL MIX" title="Channel performance" description={`${report.channels.length} marketing channels compared using the selected attribution model.`} />
    <section className="panel chart-panel"><div className="panel-heading"><div><h2>Attributed revenue and spend</h2><p>Compare investment with revenue contribution</p></div></div><div className="chart-box channel-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.channels} margin={{ top: 10, right: 10, bottom: 4, left: 8 }}><CartesianGrid stroke="#edf0f5" vertical={false} /><XAxis dataKey="channel" axisLine={false} tickLine={false} tick={{ fill: "#788398", fontSize: 10 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#788398", fontSize: 10 }} tickFormatter={formatCompactCurrency} /><Tooltip formatter={(value) => formatCurrency(Number(value))} /><Bar dataKey="spend" name="Spend" fill="#d7dcf5" radius={[4, 4, 0, 0]} isAnimationActive={false} /><Bar dataKey="attributedRevenue" name="Attributed revenue" fill="#5a58d6" radius={[4, 4, 0, 0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div></section>
    <section className="panel table-panel"><div className="panel-heading"><div><h2>Channel detail</h2><p>All metrics calculated from the uploaded campaigns and touchpoints</p></div></div><div className="table-scroll"><table><thead><tr><th>Channel</th><th>Spend</th><th>Impressions</th><th>Clicks</th><th>Sessions</th><th>Leads</th><th>Conversions</th><th>Revenue</th><th>Attributed</th><th>CTR</th><th>CPC</th><th>CVR</th><th>CAC</th><th>AOV</th><th>ROAS</th><th>ROI</th></tr></thead><tbody>{report.channels.map((item) => <tr key={item.channel}><td><strong>{item.channel}</strong><small>{item.description}</small></td><td>{formatCurrency(item.spend)}</td><td>{formatNumber(item.impressions)}</td><td>{formatNumber(item.clicks)}</td><td>{formatNumber(item.sessions)}</td><td>{formatNumber(item.leads)}</td><td>{formatNumber(item.conversions, 2)}</td><td>{formatCurrency(item.revenue)}</td><td>{formatCurrency(item.attributedRevenue)}</td><td>{formatPercent(item.ctr)}</td><td>{formatCurrency(item.cpc)}</td><td>{formatPercent(item.conversionRate)}</td><td>{formatCurrency(item.cac)}</td><td>{formatCurrency(item.aov)}</td><td className="roas-cell">{formatRoas(item.roas)}</td><td>{formatPercent(item.roi)}</td></tr>)}</tbody></table></div></section>
  </main>;
}
